import Head from 'next/head'
import Home from '../components/Home/Home';


export default function App() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>        
      <Home/>
    </div>
  )
}
